<div class="cart">
    <h1>Shopping Cart</h1>
    <div class="cart-items">
        <?php foreach ($this->getQuoteItems() as $quoteItem): ?>
            <div class="cart-item">
                <img src=<?php echo $this->getUrl('media/product/sample.jpg') ?> alt="Product Img">
                <div class="item-details">
                    <h2>
                        <?php echo $quoteItem->getProduct()->getName() ?>
                    </h2>
                    <p>
                        <?php echo "Price: &#8377;" . $quoteItem->getPrice() ?>
                    </p>
                    <p>
                        <?php echo "Quantity: " . $quoteItem->getQty() ?>
                    </p>
                </div>
                <div class="item-actions">
                    <form action="<?php echo $this->getUrl('sales/quote/delete') ?>" method="post">
                        <input type="hidden" name="item_id" value="<?php echo $quoteItem->getItemId() ?>">
                        <input type="submit" name="submit" value="Delete Item">
                    </form>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="cart-summary">
        <p>
            <?php echo "Total Price: &#8377;" . $this->getQuote()->getGrandTotal() ?>
        </p>
        <button class="checkout-btn">Checkout</button>
    </div>
</div>