<div class="list">
    <h2>Order List</h2>
    <table>
        <thead>
            <tr>
                <th>Order Number</th>
                <th>Total (in Rs.)</th>
                <th>Tax Percent (in %)</th>
                <th>Status</th>
                <th>Customer</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->getAllOrders() as $order): ?>
                <tr>
                    <td>
                        <?php echo $order->getOrderNumber() ?>
                    </td>
                    <td>
                        <?php echo "&#8377;" . $order->getGrandTotal() ?>
                    </td>
                    <td>
                        <?php echo $order->getTaxPercent() ?>
                    </td>
                    <td class="order-status" status="<?php echo $order->getStatus() ?>">
                        <b>
                            <?php echo ucfirst($order->getStatus()) ?>
                        </b>
                    </td>
                    <td>
                        <?php echo $this->getCustomerName($order->getCustomerId()) ?>
                    </td>
                    <td>
                        <a href="<?php echo $this->getUrl("admin/order/view?order_id={$order->getId()}") ?>">
                            View
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>