<?php
// echo $this->getRender('text', ['label' => 'Text', 'id' => 'text']);
// echo $this->getRender('password', ['label' => 'Password', 'id' => 'password']);
// die;
?>

<div class="container">
    <div class="form">
        <h2>Customer Login</h2>
        <form method="POST" action="<?php echo $this->getUrl('customer/account/login') ?>">
            <div class="row">
                <div>
                    <label for="customer_email">Email:</label>
                    <input type="email" required value="" name="customer[customer_email]" id="customer_email">
                </div>
                <div>
                    <label for="password">Password:</label>
                    <input type="password" required value="" name="customer[password]" id="password">
                </div>
            </div>
            <div>
                <input type="submit" name="submit" value="Submit">
            </div>
        </form>
        <p>Browse products without login? <a href="<?php echo $this->getUrl('') ?>">click here</a>
        <p>Forgot your password? <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>">click here</a>
        <p>Don't have an acoount? <a href="<?php echo $this->getUrl('customer/account/register') ?>">click here</a></p>
        </p>
    </div>
</div>