<?php
$bannerData = $this->getBanner();
?>

<div class="form">
    <h2>Banner Form</h2>
    <form method="POST" action="<?php echo $this->getUrl('admin/banner/save') ?>" enctype="multipart/form-data">
        <div>
            <input type="hidden" value="<?php echo $bannerData->getBannerId() ?>" name="banner[banner_id]">
        </div>
        <div class="row">
            <div>
                <label for="name">Banner Image:</label>
                <input type="file" value="<?php echo $bannerData->getBannerPath() ?>" name="banner[banner_path]"
                    id="name" required accept="image/png, image/jpeg, image/jpg" />
            </div>
            <?php if ($bannerData->getBannerPath()): ?>
                <div>
                    <img src="<?php echo $bannerData->getBannerImage() ?>" alt="Banner Image">
                    <input type="hidden" value="<?php echo $bannerData->getBannerPath() ?>" name="banner_path">
                </div>
            <?php endif; ?>
            <div>
                <label for="status">Banner Status:</label>
                <select name="banner[status]" id="status" required>
                    <option value="">Please select status</option>
                    <option value='1' <?php echo $bannerData->getStatus() == 'Enabled' ? 'selected' : '' ?>>Enabled
                    </option>;
                    <option value='0' <?php echo $bannerData->getStatus() == 'Disabled' ? 'selected' : '' ?>>
                        Disabled</option>;
                </select>
            </div>
        </div>
        <div>
            <input type="submit" name="submit" value="Submit">
        </div>
    </form>
</div>