<div class="form">
    <h2>Banner Form</h2>
    <form method="POST" action="<?php echo $this->getUrl('admin/banner/save') ?>" enctype="multipart/form-data">
        <div>
            <input type="hidden" value="" name="banner[banner_id]">
        </div>
        <div class="row">
            <div>
                <label for="name">Banner Image:</label>
                <input type="file" value="" name="banner[banner_image]" id="name">
            </div>
            <div>
                <label for="status">Banner Status:</label>
                <select name="banner[status]" id="status">
                    <option value='1' class="status">Enabled</option>;
                    <option value='0' class="status">Disabled</option>;
                </select>
            </div>
        </div>
        <div>
            <input type="submit" name="submit" value="Submit">
        </div>
    </form>
</div>